/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

export interface ConvertFileResponse extends AdditionalDataHolder, Parsable {
    /**
     * The filename property
     */
    filename?: string | null;
    /**
     * The markdown property
     */
    markdown?: string | null;
    /**
     * The size property
     */
    size?: number | null;
    /**
     * The status property
     */
    status?: string | null;
}
export interface ConvertUrlResponse extends AdditionalDataHolder, Parsable {
    /**
     * The markdown property
     */
    markdown?: string | null;
    /**
     * The status property
     */
    status?: string | null;
    /**
     * The url property
     */
    url?: string | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ConvertFileResponse}
 */
// @ts-ignore
export function createConvertFileResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoConvertFileResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ConvertUrlResponse}
 */
// @ts-ignore
export function createConvertUrlResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoConvertUrlResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {HTTPValidationError}
 */
// @ts-ignore
export function createHTTPValidationErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoHTTPValidationError;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {string | SupportedFormatsResponse_noteMember1}
 */
// @ts-ignore
export function createSupportedFormatsResponse_noteFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSupportedFormatsResponse_note;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SupportedFormatsResponse_noteMember1}
 */
// @ts-ignore
export function createSupportedFormatsResponse_noteMember1FromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSupportedFormatsResponse_noteMember1;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SupportedFormatsResponse}
 */
// @ts-ignore
export function createSupportedFormatsResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSupportedFormatsResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UrlPayload}
 */
// @ts-ignore
export function createUrlPayloadFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUrlPayload;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ValidationError}
 */
// @ts-ignore
export function createValidationErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoValidationError;
}
/**
 * The deserialization information for the current model
 * @param ConvertFileResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoConvertFileResponse(convertFileResponse: Partial<ConvertFileResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "filename": n => { convertFileResponse.filename = n.getStringValue(); },
        "markdown": n => { convertFileResponse.markdown = n.getStringValue(); },
        "size": n => { convertFileResponse.size = n.getNumberValue(); },
        "status": n => { convertFileResponse.status = n.getStringValue() ?? "success"; },
    }
}
/**
 * The deserialization information for the current model
 * @param ConvertUrlResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoConvertUrlResponse(convertUrlResponse: Partial<ConvertUrlResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "markdown": n => { convertUrlResponse.markdown = n.getStringValue(); },
        "status": n => { convertUrlResponse.status = n.getStringValue() ?? "success"; },
        "url": n => { convertUrlResponse.url = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param HTTPValidationError The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoHTTPValidationError(hTTPValidationError: Partial<HTTPValidationError> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "detail": n => { hTTPValidationError.detail = n.getCollectionOfObjectValues<ValidationError>(createValidationErrorFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param SupportedFormatsResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSupportedFormatsResponse(supportedFormatsResponse: Partial<SupportedFormatsResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "note": n => { supportedFormatsResponse.note = n.getStringValue() ?? n.getObjectValue<SupportedFormatsResponse_noteMember1>(createSupportedFormatsResponse_noteMember1FromDiscriminatorValue); },
        "supported_formats": n => { supportedFormatsResponse.supportedFormats = n.getCollectionOfPrimitiveValues<string>(); },
    }
}
/**
 * The deserialization information for the current model
 * @param SupportedFormatsResponse_note The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSupportedFormatsResponse_note(supportedFormatsResponse_note: Partial<Parsable | string | SupportedFormatsResponse_noteMember1> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "" : n => { supportedFormatsResponse_note = n.getStringValue()},
        ...deserializeIntoSupportedFormatsResponse_noteMember1(supportedFormatsResponse_note as SupportedFormatsResponse_noteMember1),
    }
}
/**
 * The deserialization information for the current model
 * @param SupportedFormatsResponse_noteMember1 The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSupportedFormatsResponse_noteMember1(supportedFormatsResponse_noteMember1: Partial<SupportedFormatsResponse_noteMember1> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param UrlPayload The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUrlPayload(urlPayload: Partial<UrlPayload> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "url": n => { urlPayload.url = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ValidationError The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoValidationError(validationError: Partial<ValidationError> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "loc": n => { validationError.loc = n.getCollectionOfPrimitiveValues<string>(); },
        "msg": n => { validationError.msg = n.getStringValue(); },
        "type": n => { validationError.type = n.getStringValue(); },
    }
}
export interface HTTPValidationError extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The detail property
     */
    detail?: ValidationError[] | null;
}
/**
 * Serializes information the current object
 * @param ConvertFileResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeConvertFileResponse(writer: SerializationWriter, convertFileResponse: Partial<ConvertFileResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!convertFileResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("filename", convertFileResponse.filename);
    writer.writeStringValue("markdown", convertFileResponse.markdown);
    writer.writeNumberValue("size", convertFileResponse.size);
    writer.writeStringValue("status", convertFileResponse.status ?? "success");
    writer.writeAdditionalData(convertFileResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param ConvertUrlResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeConvertUrlResponse(writer: SerializationWriter, convertUrlResponse: Partial<ConvertUrlResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!convertUrlResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("markdown", convertUrlResponse.markdown);
    writer.writeStringValue("status", convertUrlResponse.status ?? "success");
    writer.writeStringValue("url", convertUrlResponse.url);
    writer.writeAdditionalData(convertUrlResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param HTTPValidationError The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeHTTPValidationError(writer: SerializationWriter, hTTPValidationError: Partial<HTTPValidationError> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!hTTPValidationError || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<ValidationError>("detail", hTTPValidationError.detail, serializeValidationError);
    writer.writeAdditionalData(hTTPValidationError.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SupportedFormatsResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSupportedFormatsResponse(writer: SerializationWriter, supportedFormatsResponse: Partial<SupportedFormatsResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!supportedFormatsResponse || isSerializingDerivedType) { return; }
    if ( typeof supportedFormatsResponse.note === "string") {
        writer.writeStringValue("note", supportedFormatsResponse.note as string);
    }
    else {
        writer.writeObjectValue<SupportedFormatsResponse_noteMember1>("note", supportedFormatsResponse.note as SupportedFormatsResponse_noteMember1 | undefined | null, serializeSupportedFormatsResponse_note);
    }
    writer.writeCollectionOfPrimitiveValues<string>("supported_formats", supportedFormatsResponse.supportedFormats);
    writer.writeAdditionalData(supportedFormatsResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SupportedFormatsResponse_note The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSupportedFormatsResponse_note(writer: SerializationWriter, supportedFormatsResponse_note: Partial<Parsable | SupportedFormatsResponse_noteMember1> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    serializeSupportedFormatsResponse_noteMember1(writer, supportedFormatsResponse_note as SupportedFormatsResponse_noteMember1);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SupportedFormatsResponse_noteMember1 The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSupportedFormatsResponse_noteMember1(writer: SerializationWriter, supportedFormatsResponse_noteMember1: Partial<SupportedFormatsResponse_noteMember1> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!supportedFormatsResponse_noteMember1 || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(supportedFormatsResponse_noteMember1.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UrlPayload The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUrlPayload(writer: SerializationWriter, urlPayload: Partial<UrlPayload> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!urlPayload || isSerializingDerivedType) { return; }
    writer.writeStringValue("url", urlPayload.url);
    writer.writeAdditionalData(urlPayload.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ValidationError The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeValidationError(writer: SerializationWriter, validationError: Partial<ValidationError> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!validationError || isSerializingDerivedType) { return; }
    writer.writeCollectionOfPrimitiveValues<string>("loc", validationError.loc);
    writer.writeStringValue("msg", validationError.msg);
    writer.writeStringValue("type", validationError.type);
    writer.writeAdditionalData(validationError.additionalData);
}
export interface SupportedFormatsResponse extends AdditionalDataHolder, Parsable {
    /**
     * The note property
     */
    note?: string | SupportedFormatsResponse_noteMember1 | null;
    /**
     * The supported_formats property
     */
    supportedFormats?: string[] | null;
}
export type SupportedFormatsResponse_note = string | SupportedFormatsResponse_noteMember1;
export interface SupportedFormatsResponse_noteMember1 extends AdditionalDataHolder, Parsable {
}
export interface UrlPayload extends AdditionalDataHolder, Parsable {
    /**
     * The url property
     */
    url?: string | null;
}
export interface ValidationError extends AdditionalDataHolder, Parsable {
    /**
     * The loc property
     */
    loc?: string[] | null;
    /**
     * The msg property
     */
    msg?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
/* tslint:enable */
/* eslint-enable */
