/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createConvertFileResponseFromDiscriminatorValue, createHTTPValidationErrorFromDiscriminatorValue, type ConvertFileResponse, type HTTPValidationError } from '../models/index.js';
// @ts-ignore
import { MultipartBody, serializeMultipartBody, type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /convert
 */
export interface ConvertRequestBuilder extends BaseRequestBuilder<ConvertRequestBuilder> {
    /**
     * Convert Document
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ConvertFileResponse>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     post(body: MultipartBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ConvertFileResponse | undefined>;
    /**
     * Convert Document
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: MultipartBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ConvertRequestBuilderUriTemplate = "{+baseurl}/convert";
/**
 * Metadata for all the requests in the request builder.
 */
export const ConvertRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ConvertRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createConvertFileResponseFromDiscriminatorValue,
        requestBodyContentType: "multipart/form-data",
        requestBodySerializer: serializeMultipartBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
