/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createConvertUrlResponseFromDiscriminatorValue, createHTTPValidationErrorFromDiscriminatorValue, serializeConvertUrlResponse, serializeUrlPayload, type ConvertUrlResponse, type HTTPValidationError, type UrlPayload } from '../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /convert-url
 */
export interface ConvertUrlRequestBuilder extends BaseRequestBuilder<ConvertUrlRequestBuilder> {
    /**
     * Convert From Url
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ConvertUrlResponse>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     post(body: UrlPayload, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ConvertUrlResponse | undefined>;
    /**
     * Convert From Url
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: UrlPayload, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ConvertUrlRequestBuilderUriTemplate = "{+baseurl}/convert-url";
/**
 * Metadata for all the requests in the request builder.
 */
export const ConvertUrlRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ConvertUrlRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createConvertUrlResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeUrlPayload,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
