// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MyCompany.PythonApi.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SupportedFormatsResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The note property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MyCompany.PythonApi.Models.SupportedFormatsResponse.SupportedFormatsResponse_note? Note { get; set; }
#nullable restore
#else
        public global::MyCompany.PythonApi.Models.SupportedFormatsResponse.SupportedFormatsResponse_note Note { get; set; }
#endif
        /// <summary>The supported_formats property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? SupportedFormats { get; set; }
#nullable restore
#else
        public List<string> SupportedFormats { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MyCompany.PythonApi.Models.SupportedFormatsResponse"/> and sets the default values.
        /// </summary>
        public SupportedFormatsResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MyCompany.PythonApi.Models.SupportedFormatsResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MyCompany.PythonApi.Models.SupportedFormatsResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::MyCompany.PythonApi.Models.SupportedFormatsResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "note", n => { Note = n.GetObjectValue<global::MyCompany.PythonApi.Models.SupportedFormatsResponse.SupportedFormatsResponse_note>(global::MyCompany.PythonApi.Models.SupportedFormatsResponse.SupportedFormatsResponse_note.CreateFromDiscriminatorValue); } },
                { "supported_formats", n => { SupportedFormats = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::MyCompany.PythonApi.Models.SupportedFormatsResponse.SupportedFormatsResponse_note>("note", Note);
            writer.WriteCollectionOfPrimitiveValues<string>("supported_formats", SupportedFormats);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MyCompany.PythonApi.Models.SupportedFormatsResponse_noteMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SupportedFormatsResponse_note : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::MyCompany.PythonApi.Models.SupportedFormatsResponse_noteMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MyCompany.PythonApi.Models.SupportedFormatsResponse_noteMember1? SupportedFormatsResponseNoteMember1 { get; set; }
#nullable restore
#else
            public global::MyCompany.PythonApi.Models.SupportedFormatsResponse_noteMember1 SupportedFormatsResponseNoteMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MyCompany.PythonApi.Models.SupportedFormatsResponse.SupportedFormatsResponse_note"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MyCompany.PythonApi.Models.SupportedFormatsResponse.SupportedFormatsResponse_note CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MyCompany.PythonApi.Models.SupportedFormatsResponse.SupportedFormatsResponse_note();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.SupportedFormatsResponseNoteMember1 = new global::MyCompany.PythonApi.Models.SupportedFormatsResponse_noteMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(SupportedFormatsResponseNoteMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(SupportedFormatsResponseNoteMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                _ = writer ?? throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::MyCompany.PythonApi.Models.SupportedFormatsResponse_noteMember1>(null, SupportedFormatsResponseNoteMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
