/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createSupportedFormatsResponseFromDiscriminatorValue, type SupportedFormatsResponse } from '../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /supported-formats
 */
export interface SupportedFormatsRequestBuilder extends BaseRequestBuilder<SupportedFormatsRequestBuilder> {
    /**
     * Get Supported Formats
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SupportedFormatsResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SupportedFormatsResponse | undefined>;
    /**
     * Get Supported Formats
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const SupportedFormatsRequestBuilderUriTemplate = "{+baseurl}/supported-formats";
/**
 * Metadata for all the requests in the request builder.
 */
export const SupportedFormatsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: SupportedFormatsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createSupportedFormatsResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
